version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: foodcart_postgres
    environment:
      POSTGRES_DB: foodcart
      POSTGRES_USER: foodcart_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: foodcart_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: foodcart_keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: foodcart_user
      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  mailpit:
    image: axllent/mailpit
    container_name: foodcart_mailpit
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP
    restart: unless-stopped

volumes:
  pg_data:
  mongo_data:
